### ISSUE TITLE
Proposal: subgraph structure

### ISSUE THREAD

**Issue by benjaminreid** [simpleweb/open-format#37]
Currently we initialise the SDK like so to interact with the subgraph...

```tsx
const sdk = new OpenFormatSDK({
  network: 'mumbai',
});

await sdk.getSaleDataForToken('0x...');
```

The query here (and many more that are yet to be added) will probably want a "factory id" passing to them to scope the results to a certain factory, rather than entire Open Format graph.

Now, there's kind of some different ways we can go about this.

Pass the factory ID into every subgraph call, which would work although a little tedious when you may want to call multiple different functions throughout your app.

```tsx
await sdk.getSaleDataForToken({ factoryId: "0x...", tokenId: "0x..." });
```

Creating an instance off the subgraph off the instance of the SDK

```tsx
const sdk = new OpenFormatSDK({
  network: 'mumbai',
});

const subgraph = new sdk.subgraph({ factory: "0x..." });

subgraph.getSaleDataForToken("0x...");
```

Pass a factory ID when creating a new SDK instance

```tsx
const sdk = new OpenFormatSDK({
  network: 'mumbai',
  factoryId: "0x...",
});

await sdk.getSaleDataForToken('0x...');
```

Or something totally different?!

Be good to get your thoughts on this @coatezy @tinypell3ts @Sam-Archie

**Comment by tinypell3ts** [comment]
This looks great @benjaminreid . Even though our previous conversation was leaning more towards only passing a factory ID when querying the subgraph, I think it will be beneficial to pass a factory ID when creating a new SDK instance. My reasons being:

1. All current projects to date have been scoped to a single factory ID.
2. Due to the above (and my opinion), it's unlikely users will want to scope the SDK and subgraph separately. The only use case I can think of where a developer will not want to scope the subgraph would be if they're only creating a frontend for listing NFT's, rather than deploying and interacting.
